In [1]:
import pandas as pd

In [2]:
Chicago_data = 'https://raw.githubusercontent.com/terranigmark/curso-analisis-exploratorio-datos-platzi/main/Traffic_Crashes1.csv'
Chicago_df=pd.read_csv(Chicago_data)

In [3]:
Chicago_df['CRASH_DATE'] = Chicago_df['CRASH_DATE'].apply(lambda x: pd.to_datetime(x,errors='coerce', utc=True))
Chicago_df.groupby(['LIGHTING_CONDITION','REPORT_TYPE','CRASH_HOUR']).agg({'BEAT_OF_OCCURRENCE':'sum',})

                                                          BEAT_OF_OCCURRENCE
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                      1614.0
                   NOT ON SCENE (DESK REPORT) 0                      64739.0
                                              1                      60086.0
                                              2                      36251.0
                                              3                      39172.0
...                                                                      ...
UNKNOWN            ON SCENE                   19                      4735.0
                                              20                      8113.0
                                              21                      6122.0
                                              22                      9699.0
                                              23                      3176.0

[291 rows x 1 columns]

Tabla pivote otro metodo

In [7]:
pd.pivot_table(Chicago_df,index=['LIGHTING_CONDITION','REPORT_TYPE','CRASH_HOUR'])

                                                          BEAT_OF_OCCURRENCE  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                 1614.000000
                   NOT ON SCENE (DESK REPORT) 0                  1269.392157
                                              1                  1365.590909
                                              2                  1208.366667
                                              3                  1350.758621
...                                                                      ...
UNKNOWN            ON SCENE                   19                  947.000000
                                              20                 1622.600000
                                              21                 1224.400000
                                              22                 1077.666667
                                              23                 1058.666667

                                                          CRASH_DAY_OF_WEEK  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                   5.000000
                   NOT ON SCENE (DESK REPORT) 0                    3.823529
                                              1                    3.636364
                                              2                    3.033333
                                              3                    3.448276
...                                                                     ...
UNKNOWN            ON SCENE                   19                   4.400000
                                              20                   5.600000
                                              21                   4.200000
                                              22                   5.000000
                                              23                   3.666667

                                                          CRASH_MONTH  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20             6.000000
                   NOT ON SCENE (DESK REPORT) 0              7.019608
                                              1              7.204545
                                              2              5.733333
                                              3              7.310345
...                                                               ...
UNKNOWN            ON SCENE                   19            10.200000
                                              20             4.200000
                                              21             5.000000
                                              22             7.333333
                                              23             5.666667

                                                          INJURIES_FATAL  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                     0.0
                   NOT ON SCENE (DESK REPORT) 0                      0.0
                                              1                      0.0
                                              2                      0.0
                                              3                      0.0
...                                                                  ...
UNKNOWN            ON SCENE                   19                     0.0
                                              20                     0.0
                                              21                     0.0
                                              22                     0.0
                                              23                     0.0

                                                          INJURIES_INCAPACITATING  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                         0.000000
                   NOT ON SCENE (DESK REPORT) 0                          0.000000
                                              1                          0.000000
                                              2                          0.033333
                                              3                          0.000000
...                                                                           ...
UNKNOWN            ON SCENE                   19                         0.200000
                                              20                         0.000000
                                              21                         0.000000
                                              22                         0.000000
                                              23                         0.000000

                                                          INJURIES_NON_INCAPACITATING  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                             0.000000
                   NOT ON SCENE (DESK REPORT) 0                              0.000000
                                              1                              0.045455
                                              2                              0.000000
                                              3                              0.000000
...                                                                               ...
UNKNOWN            ON SCENE                   19                             0.600000
                                              20                             0.000000
                                              21                             0.000000
                                              22                             0.111111
                                              23                             0.000000

                                                          INJURIES_NO_INDICATION  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                        2.000000
                   NOT ON SCENE (DESK REPORT) 0                         1.725490
                                              1                         1.750000
                                              2                         1.733333
                                              3                         1.551724
...                                                                          ...
UNKNOWN            ON SCENE                   19                        1.600000
                                              20                        1.000000
                                              21                        1.200000
                                              22                        1.111111
                                              23                        2.000000

                                                          INJURIES_REPORTED_NOT_EVIDENT  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                               0.000000
                   NOT ON SCENE (DESK REPORT) 0                                0.000000
                                              1                                0.068182
                                              2                                0.033333
                                              3                                0.000000
...                                                                                 ...
UNKNOWN            ON SCENE                   19                               0.000000
                                              20                               0.000000
                                              21                               0.000000
                                              22                               0.111111
                                              23                               0.000000

                                                          INJURIES_TOTAL  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                0.000000
                   NOT ON SCENE (DESK REPORT) 0                 0.000000
                                              1                 0.113636
                                              2                 0.066667
                                              3                 0.000000
...                                                                  ...
UNKNOWN            ON SCENE                   19                0.800000
                                              20                0.000000
                                              21                0.000000
                                              22                0.222222
                                              23                0.000000

                                                          INJURIES_UNKNOWN  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                       0.0
                   NOT ON SCENE (DESK REPORT) 0                        0.0
                                              1                        0.0
                                              2                        0.0
                                              3                        0.0
...                                                                    ...
UNKNOWN            ON SCENE                   19                       0.0
                                              20                       0.0
                                              21                       0.0
                                              22                       0.0
                                              23                       0.0

                                                          LANE_CNT   LATITUDE  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20          2.000000  41.954006
                   NOT ON SCENE (DESK REPORT) 0           6.000000  41.859932
                                              1           2.300000  41.856003
                                              2           2.117647  41.859911
                                              3           2.187500  41.830497
...                                                            ...        ...
UNKNOWN            ON SCENE                   19          3.000000  41.850931
                                              20          1.000000  41.917053
                                              21          2.000000  41.843184
                                              22          1.250000  41.857974
                                              23          1.000000  41.864409

                                                          LONGITUDE  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20         -87.835332
                   NOT ON SCENE (DESK REPORT) 0          -87.673046
                                              1          -87.679442
                                              2          -87.680107
                                              3          -87.688692
...                                                             ...
UNKNOWN            ON SCENE                   19         -87.646468
                                              20         -87.644605
                                              21         -87.640647
                                              22         -87.675291
                                              23         -87.652587

                                                          NUM_UNITS  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20           2.000000
                   NOT ON SCENE (DESK REPORT) 0            1.901961
                                              1            1.954545
                                              2            2.133333
                                              3            1.965517
...                                                             ...
UNKNOWN            ON SCENE                   19           1.800000
                                              20           2.000000
                                              21           2.000000
                                              22           2.222222
                                              23           2.000000

                                                          POSTED_SPEED_LIMIT  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20                   30.000000
                   NOT ON SCENE (DESK REPORT) 0                    29.019608
                                              1                    27.272727
                                              2                    29.000000
                                              3                    27.068966
...                                                                      ...
UNKNOWN            ON SCENE                   19                   31.000000
                                              20                   24.000000
                                              21                   28.000000
                                              22                   25.555556
                                              23                   26.666667

                                                            STREET_NO  \
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20          8324.000000
                   NOT ON SCENE (DESK REPORT) 0           3360.960784
                                              1           3149.000000
                                              2           3666.233333
                                              3           4657.827586
...                                                               ...
UNKNOWN            ON SCENE                   19          3389.600000
                                              20          2402.600000
                                              21          1348.200000
                                              22          3788.888889
                                              23          1619.333333

                                                             Unnamed: 0
LIGHTING_CONDITION REPORT_TYPE                CRASH_HOUR
DARKNESS           AMENDED                    20          322381.000000
                   NOT ON SCENE (DESK REPORT) 0           211505.411765
                                              1           217669.295455
                                              2           200583.700000
                                              3           229263.931034
...                                                                 ...
UNKNOWN            ON SCENE                   19          208334.800000
                                              20          238466.600000
                                              21          186882.000000
                                              22           75801.666667
                                              23          252801.666667

[291 rows x 17 columns]

# filter

In [8]:
Chicago_df.filter(['LIGHTING_CONDITION','REPORT_TYPE','CRASH_HOUR'])

      LIGHTING_CONDITION                 REPORT_TYPE  CRASH_HOUR
0               DAYLIGHT  NOT ON SCENE (DESK REPORT)          10
1               DAYLIGHT                    ON SCENE          19
2               DAYLIGHT                    ON SCENE           8
3                UNKNOWN                    ON SCENE          16
4               DAYLIGHT  NOT ON SCENE (DESK REPORT)           8
...                  ...                         ...         ...
27956           DAYLIGHT                    ON SCENE           9
27957           DAYLIGHT  NOT ON SCENE (DESK REPORT)           9
27958           DAYLIGHT                    ON SCENE          13
27959           DAYLIGHT  NOT ON SCENE (DESK REPORT)           9
27960            UNKNOWN  NOT ON SCENE (DESK REPORT)          10

[27961 rows x 3 columns]

# crosstab

In [11]:
pd.crosstab(Chicago_df['LIGHTING_CONDITION'],Chicago_df["BEAT_OF_OCCURRENCE"])

BEAT_OF_OCCURRENCE,111.0,112.0,113.0,114.0,121.0,122.0,123.0,124.0,131.0,132.0,...,2521.0,2522.0,2523.0,2524.0,2525.0,2531.0,2532.0,2533.0,2534.0,2535.0
LIGHTING_CONDITION,,,,,,,,,,,,,,,,,,,,,
DARKNESS,2,3,3,14,5,13,4,5,7,8,...,9,3,4,5,1,7,3,12,1,3
"DARKNESS, LIGHTED ROAD",32,20,16,62,22,52,30,33,39,42,...,32,18,23,22,14,20,25,31,22,27
DAWN,2,3,2,8,3,4,3,3,3,1,...,4,3,0,4,1,2,1,2,2,1
DAYLIGHT,102,71,59,174,118,213,146,108,138,109,...,97,65,68,55,39,40,49,119,75,52
DUSK,6,3,0,6,2,10,6,5,8,3,...,11,4,4,1,2,1,4,4,6,1
UNKNOWN,1,1,2,12,0,6,3,5,2,2,...,5,6,5,1,4,0,6,2,8,5